### PR TITLE
Allows to edit settings when File History packed..

### PR DESCRIPTION
**Pull request by Argimko**
into .sublime-package

### CODE REVIEW

**Comment by FichteFoll** [comment]
Does this actually make a difference? As in, it didn't work for you before?

**Comment by Argimko** [comment]
I think it is honest if we take "Package Control.sublime-package" as a reference example.
You can find inside it Main.sublime-menu which has "${packages}" variable instead of "$package".

Seems $package variable works only if package is Not packed inside ".sublime-package".

I am using ST build 3208.

By the way, thank you for your package)

**Comment by FichteFoll** [comment]
All right, I can confirm this with:
```py
window.run_command("open_file", {"file": "$packages/Default/Preferences.sublime-settings"})
# vs
window.run_command("open_file", {"file": "${packages}/Default/Preferences.sublime-settings"})
```

That's an interesting issue and good to know. I wonder why the open_file command doesn't use the same templating syntax as all other parts of ST (snippets, `sublime.expand_variables`), but this may be in order to prevent normal dollar signs in file paths to accidentally trigger a variable replacement.

Anyway, I confirmed this, but I'll switch the package to use the `edit_settings` command instead.

**Comment by Argimko** [comment]
Okay, thank you!

**Comment by FichteFoll** [comment]
Because usage of `edit_settings` breaks ST2 compatibility, I'll need to prepare a new release channel for this package to still allow ST2 users (which are admittedly **very** few) to install the package. But the effort required for me to do that is minimal, so I'll provide a legacy ST2 release for the forseeable future. 1.8.2 will be the last release to support ST2.

I'll include this in the next update when someone finds something to work on again.

**Pull request closed without merging**
